### ISSUE TITLE
Probably wrong behaviour with dynamic.enabled=false

### ISSUE THREAD

**Issue by r0ssIV** [symfony-cmf/routing-bundle#110]
Initial sandbox configuration:

``` yml
cmf_routing:
    route_basepath: /cms/routes
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        controllers_by_type:
            demo_type: sandbox_main.controller:typeAction
        controllers_by_class:
            Sandbox\MainBundle\Document\DemoClassContent: sandbox_main.controller:classAction
            Symfony\Cmf\Bundle\RoutingBundle\Document\RedirectRoute:  cmf_routing.redirect_controller:redirectAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Blog: cmf_blog.blog_controller:listAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Post: cmf_blog.blog_controller:viewPostAction

        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\MultilangStaticContent: MMPGlobalServicesBundle:MultilangStaticContent:index.html.twig

        locales: %locales%
```

If we set dynamic.enabled=false, instead of simply removing dynamic router from chain, it throws exception
RuntimeException: The parent definition "cmf_routing.enhancer_explicit_template" defined for definition "cmf_simple_cms.enhancer_explicit_template" does not exist

If we simply comment out

``` yml
#            cmf_routing.dynamic_router: 20
```

the exception does not happen
