### ISSUE TITLE
/routes wont be removed from urls

### ISSUE THREAD

**Issue by digitalkaoz** [symfony-cmf/routing-bundle#114]
Hey i am using `beta-1` of the symfony-cmf standard edition. and i like it very much :) thanks for the good work!

here is my problem:

**nodes dump**

```
ROOT:
  cms:
    routes:
      home:
    menu:
      home:
    content:
      static:
      home:
```

**routing.yml**

``` yaml
home_redirect:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: /cms/routes/home
        permanent: true
```

**config.yml**

``` yaml
cmf_routing:
#    route_basepath: /cms/routes
    dynamic:
        enabled: true
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
```

if i try to access `/` in my browser i am redirected to `/routes/home`, that `/routes/` is to much.
if i try to access `/home` i am getting a 404...

how to remove the `routes/`prefix? even if i try to set the `route_basepath` to `/cms/routes` it wont work.

any hints?
