### ISSUE TITLE
Fire event before RouteProvider

### ISSUE THREAD

**Issue by trsteel88** [symfony-cmf/routing-bundle#119]
Is there an event I can create a listener for that is loaded before the RouteProvider?

I need to load an SQLFilter before the RouteProvider. At the moment I am listening to onKernelRequest but it does not load before the RouteProvider. I tried priority -255.

``` yaml
    vivo_site.listener.site_aware_filter:
        class: Vivo\SiteBundle\EventListener\SiteAwareFilterListener
        arguments:
            - @vivo_site.context.site
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
```
