### ISSUE TITLE
Doctrine manager register

### ISSUE THREAD

**Issue by trsteel88** [symfony-cmf/routing-bundle#124]
I just noticed the config has updated so that "manager_registry" was moved under the "phpcr_provider" node.

If I don't set my manager_register to "doctrine" I get errors.

Here is what I had:

``` yaml
cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        route_provider_service_id: vivo_page.routing.provider
        manager_registry: doctrine
```

I have updated it so that it is now:

``` yaml
cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        route_provider_service_id: vivo_page.routing.provider
        phpcr_provider:
            manager_registry: doctrine
```

And it works again. However, why is the manager register under a phpcr node if its not related to phpcr?

If I don't set a manager_register I get the following error:

```
 [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                            
  The service "cmf_routing.generator" has a dependency on a non-existent service "cmf_routing.content_  
  repository". 
```
