### ISSUE TITLE
parameter not found exception

### ISSUE THREAD

**Issue by oscargala** [symfony-cmf/routing-bundle#169]
Hi,

I'm trying to create a custom route repository from the cookbook: http://symfony.com/doc/current/cmf/cookbook/using_a_custom_route_repository.html

It states that the minimum configuration would be:

```
# app/config/config.yml
cmf_routing:
    dynamic:
        enabled: true
        route_provider_service_id: acme_demo.provider.endpoint
```

If I use that however, I get the following error:

Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException' with message 'The service "cmf_routing.enhancer_controller_for_templates_by_class" has a dependency on a non-existent parameter "cmf_routing.defined_templates_class". Did you mean one of these: "cmf_routing.templates_by_class", "cmf_routing.nested_matcher_class", "cmf_routing.final_matcher_class"

Any ideas on how this can be fixed?
