### ISSUE TITLE
Routes not loaded in console

### ISSUE THREAD

**Issue by trsteel88** [symfony-cmf/routing-bundle#208]
I have the following config:

``` yaml
cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        route_provider_service_id: vivo_page.routing.provider
```

When I execute app/console router:debug the routes do not show up. Is there an issue with my config or does the bundle not support this?
