### ISSUE TITLE
MIssing RouteProvider

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/routing-bundle#439]
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In CmfRoutingExtension.php line 132:
!!                                                                                 
!!    When the dynamic router is enabled, you need to either enable one of the pe  
!!    rsistence layers or set the cmf_routing.dynamic.route_provider_service_id o  
!!    ption                                                                        
!!                                                                                 
!!  
!!  
```
That occured from one day to an other with the same dependencies (that i can see)

config:

```

cmf_routing:
    persistence:
        phpcr: ~
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        route_collection_limit: 10
        templates_by_class:
            App\Document\BlogPage: static_content/article.html.twig
            App\Document\StaticPage: static_content/index.html.twig
```
