### ISSUE TITLE
Get Router Matcher

### ISSUE THREAD

**Issue by trsteel88** [symfony-cmf/routing-bundle#88]
I am trying to create a RouteValidator. I have a validator for validating a Route for the Symfony Router. However, it fails for the CMF Routing because there isn't a getMatcher method. Is there a way I can check if a route is already taken?

https://gist.github.com/trsteel88/5572570

fyi, I tried using the match method (https://github.com/symfony-cmf/RoutingBundle/blob/master/Routing/DynamicRouter.php#L65). However, a exception is thrown if there is no match. Is this normal?

```
Catchable Fatal Error: Argument 1 passed to Symfony\Cmf\Bundle\RoutingExtraBundle\Routing\DynamicRouter::matchRequest() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /usr/local/zend/apache2/htdocs/vivogroup/cms-dev/vendor/symfony-cmf/routing/Symfony/Cmf/Component/Routing/ChainRouter.php on line 168 and defined in /usr/local/zend/apache2/htdocs/vivogroup/cms-dev/vendor/symfony-cmf/routing-extra-bundle/Symfony/Cmf/Bundle/RoutingExtraBundle/Routing/DynamicRouter.php line 72
```

I am using the dynamic router:

``` yaml
symfony_cmf_routing_extra:
    chain:
        routers_by_id:
            symfony_cmf_routing_extra.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        route_provider_service_id: vivo_page.routing.provider
        manager_registry: doctrine
        content_repository_service_id: vivo_page.routing.content_repository
```
